Add pattern to spaczz Matcher output to ensure 0.6.0 compatibility
FAILED src/tests/legislation_extraction_tests/test_legislation_citations.py::TestLegislationProcessor::test_lookup_pipe - ValueError: too many values to unpack (expected 4)
FAILED src/tests/legislation_extraction_tests/test_legislation_citations.py::TestLegislationProcessorHelpers::test_hybrid - ValueError: too many values to unpack (expected 4)
FAILED src/tests/legislation_extraction_tests/test_legislation_citations.py::TestLegislationProcessorHelpers::test_search_for_act_fuzzy - ValueError: too many values to unpack (expected 4)

v0.6.0 Release Notes:

    Returning the matching pattern for all matchers, this is a breaking change as matches are now tuples of length 5 instead of 4.