Bump en-core-web-sm to 3.7.1 -- not reflected elsewhere
Update only the model in the tests -- we'll have to take a look at the others
later...

Hopefully fixes:
The conflict is caused by:
    The user requested spacy==3.7.2
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    spaczz 0.5.4 depends on spacy<4.0.0 and >=2.2.0
    en-core-web-sm 3.2.0 depends on spacy<3.3.0 and >=3.2.0