Fix rds cluster attributes
* For some reason, when this is being applied, the error is being
  thrown:

> Error: Invalid index
> on modules/data/aurora.tf line 20, in module "aurora-metadata-db":
>  20:   password = aws_secretsmanager_secret_version.aurora_postgress_master_password[each.key].secret_string
>    ├────────────────
>    │ aws_secretsmanager_secret_version.aurora_postgress_master_password is object with no attributes
>    │ each.key is "main"

Which is weird, because it is being created (They all use the same
local.aurora_rds in their `for_each`)

This is an attempt to add `depends_on` to force those resources to be
evaluated first